### ISSUE TITLE
sample_03_box.cpp定点着色器中的VARYING_COLOR没有在像素着色器被使用，可以去除吗？

### ISSUE THREAD

**Issue by Aglargil** [skywind3000/RenderHelp#12]
https://github.com/skywind3000/RenderHelp/blob/2d3b6057178a54423e101a6375cb920da05e6928/sample_03_box.cpp#L66
`sample_04_gouraud.cpp` 中也有这样的问题
https://github.com/skywind3000/RenderHelp/blob/2d3b6057178a54423e101a6375cb920da05e6928/sample_04_gouraud.cpp#L84

**Comment by skywind3000** [comment]
可以去除啊

**Comment by Aglargil** [comment]
好的，了解了，谢谢😄
