### ISSUE TITLE
三角形接缝处不连续，有遗漏的点

### ISSUE THREAD

**Issue by glcolor** [skywind3000/RenderHelp#2]
使用如下代码渲染四边形时发现对角线接缝处不连续，有未处理到的像素点:

```
// 初始化渲染器和帧缓存大小
RenderHelp rh(800, 600);

Mat4x4f mat_model = matrix_set_identity();	// 模型变换
Mat4x4f mat_view = matrix_set_lookat({ 0, 0, -1.5f }, { 0, 0, 0 }, { 0, 1, 0 });	// 摄像机方位
Mat4x4f mat_proj = matrix_set_perspective(3.1415926f * 0.5f, 800 / 600.0f, 0.1f, 500.0f);
Mat4x4f mat_mvp = mat_model * mat_view * mat_proj;	// 综合变换矩阵

const int VARYING_COLOR = 0;    // 定义一个 varying 的 key

struct VertexAttrib { Vec4f pos; Vec4f color; };

VertexAttrib vs_input[3];

// 顶点数据，由 VS 读取，如有多个三角形，可每次更新 vs_input 再绘制
VertexAttrib vertex[4] = {
	{ { -1.0f, -1.0f, 0.0f, 1.0f }, { 1.0f, 0.0f, 0.0f, 1.0f } },
	{ { -1.0f, 1.0f, 0.0f, 1.0f }, { 0.0f, 1.0f, 0.0f, 1.0f } },
	{ { 1.0f, 1.0f, 0.0f, 1.0f }, { 0.0f, 0.0f, 1.0f, 1.0f } },
	{ { 1.0f, -1.0f, 0.0f, 1.0f }, { 1.0f, 1.0f, 1.0f, 1.0f } },
};

// 顶点着色器，初始化 varying 并返回坐标，
// 参数 index 是渲染器传入的顶点序号，范围 [0, 2] 用于读取顶点数据
rh.SetVertexShader([&](int index, ShaderContext& output) -> Vec4f 
{
	Vec4f pos = vs_input[index].pos * mat_mvp;  // 扩充成四维矢量并变换
	output.varying_vec4f[VARYING_COLOR] = vs_input[index].color;
	return pos;
});

// 像素着色器，返回颜色
rh.SetPixelShader([&](ShaderContext& input) -> Vec4f {
	return input.varying_vec4f[VARYING_COLOR];
});

// 渲染并保存
vs_input[0] = vertex[0];
vs_input[1] = vertex[1];
vs_input[2] = vertex[2];
rh.DrawPrimitive();

vs_input[0] = vertex[2];
vs_input[1] = vertex[3];
vs_input[2] = vertex[0];
rh.DrawPrimitive();

rh.SaveFile("output.bmp");
```
![output](https://user-images.githubusercontent.com/1741084/90475837-e1cf8000-e15a-11ea-9ca7-a3a5304e3801.png)

**Comment by skywind3000** [comment]
good 我看看。

**Comment by skywind3000** [comment]
有一个点，刚好落在 p0-p1 的边上，edge equation 应该等于零的，但是由于 sse 优化引入的浮点误差，导致在第一个三角形那里被计算成 E < 0，第二个三角形还是 E < 0。

去掉 gcc 优化可以解决，不要加 -O2/ -O3。

找到那个漏点 px={400,300}，在我机器上，在你机器上不一定，第一个三角形：

```
px={400,300}
p0={200,500}
p1={600,100}
p2={200,100}

然后 当 px = {400,300} 时：

E01 = (px.x - p0.x) * (p1.y - p0.y) - (px.y - p0.y) * (p1.x - p0.x)
    = (400 - 200)*(100-500) - (300 - 500) * (600 - 200) 
    = -80000 + 80000 = 0

但是电脑算出来却是 E01 = -0.00268555
```

第二个三角形：

```
px={400,300}
p0={600,100}
p1={200,500}
p2={600,500}

E01=(px.x - p0.x) * (p1.y - p0.y) - (px.y - p0.y) * (p1.x - p0.x)
    = (400 - 600) * (500 - 100) - (300 - 100) * (200 - 600)
    = -80000 + 80000 = 0

但是电脑算出来：E01 = -0.00439453
```

![图片](https://user-images.githubusercontent.com/3035071/90495798-9e373f00-e177-11ea-86b8-0d378b6a012c.png)

所以由于编译优化，导致落在边上的点，计算过后，既不在左边的三角形内，也不再右边的三角形内。

我电脑上干掉 -O2, -O3 的选项后，一切正常，你可以试试，后续我会试试换成整数来计算。

**Comment by skywind3000** [comment]
解决了，使用整数精确计算：

https://github.com/skywind3000/RenderHelp/commit/8b58d43937d66c66592f6d592c14b04d46b4cbc3

效果：

![图片](https://user-images.githubusercontent.com/3035071/90499264-e6f0f700-e17b-11ea-8de2-23e03bd70ae8.png)

**Comment by glcolor** [comment]
确实OK了，多谢！

**Comment by skywind3000** [comment]
https://www.scratchapixel.com/lessons/3d-basic-rendering/rasterization-practical-implementation/rasterization-practical-implementation

GPU 在 NDC 空间中也是使用基于整数的定点数来计算，避免误差：

> Finally and to conclude this section, we will briefly talk about the technique that consists of converting vertex coordinates which are initially defined in floating-point format to fixed-point format just before the rasterization stage. Fixed-point is the fancy word (in the fact the correct technical term) for integer. When vertex coordinates are converted from NDC to raster space, they are then also converted from floating point numbers to fixed point numbers. Why do we do that? There is no easy and quick answer to this question. But to be short, let's just say that GPUs use fixed point arithmetic because from a computing point of view, manipulating integers is easier and faster than manipulating floats or doubles (it only requires logical bit operations). Again this is just a very generic explanation. The conversion from floating point to integer coordinates and how is the rasterization process implemented using integer coordinates is a large and complex topic which is not documented on the Internet (you will find very little information about this topic which is very strange considering that this very process is central to the way modern GPUs work).
