### ISSUE TITLE
读取其他格式的纹理图

### ISSUE THREAD

**Issue by LexTran** [skywind3000/RenderHelp#5]
你好！我是一个新手，非常感谢您提供的项目，代码很清晰，非常利于学习。
但是我发现我找不到bmp格式的文件，我想要渲染其他模型，找到的资源大都是mtl、jpg格式的纹理图，请问这个项目可以进行拓展吗，我不知道该怎么做，希望您能帮忙解答一下我该如何进行改进，感谢！

**Comment by skywind3000** [comment]
自己用画板把他们转换成 bmp 格式就可以读取了，否则程序读取 jpeg 的话，你还要引入额外的依赖。

**Comment by LexTran** [comment]
好的，我明白了，我之前直接修改的文件后缀，感谢您

**Comment by skywind3000** [comment]
我晕
